drive/urls.py
from django.conf.urls import patterns, url
from drive import views
from haystack.views import SearchView

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^logout/$', views.drive_logout, name='drive_logout'),
    url(r'^rides/new$', views.rides_new, name='rides_new'),
    url(r'^rides/$', views.rides_index, name='rides_index'),
    url(r'^rides/show/(?P<pk>\d+)$', views.rides_show, name='rides_show'),
    url(r'^profile/edit$', views.profile_edit, name='profile_edit'),
    url(r'^rides/search$', views.rides_search, name='rides_search'),
)

shotgun/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shotgun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^', include('drive.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^login/$',  login),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^uploads/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT,}),
)

drive/forms.py
from django import forms
from django.forms import ModelForm
from drive.models import ShotgunProfile

class RideForm(forms.Form):
    fromInput = forms.CharField(widget=forms.TextInput(attrs={'id':'address-from', 'class':'col-xs-12','autocomplete':'off'}), max_length=255)
    fromLat = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo':'lat'}), max_digits=20, decimal_places=16)
    fromLng = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo':'lng'}), max_digits=20, decimal_places=16)
    fromFormatted = forms.CharField(widget=forms.HiddenInput(attrs={'data-geo':'formatted_address'}), max_length=255)
    fromLocality = forms.CharField(widget=forms.HiddenInput(attrs={'data-geo':'locality'}), max_length=255)

    toInput = forms.CharField(widget=forms.TextInput(attrs={'id':'address-to', 'class':'col-xs-12','autocomplete':'off'}), max_length=255)
    toLat = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo':'lat'}), max_digits=20, decimal_places=16)
    toLng = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo':'lng'}), max_digits=20, decimal_places=16)
    toFormatted = forms.CharField(widget=forms.HiddenInput(attrs={'data-geo':'formatted_address'}), max_length=255)
    toLocality = forms.CharField(widget=forms.HiddenInput(attrs={'data-geo':'locality'}), max_length=255)

    leavingOn = forms.DateField(widget=forms.DateInput(attrs={'class':'col-xs-12','placeholder':'mm/dd/yyyy'}))
    gasMoney = forms.DecimalField(widget=forms.NumberInput(attrs={'class':'col-xs-12', 'placeholder':'5.00'}), max_digits=6, decimal_places=2)
    luggageRoom = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'col-xs-12', 'placeholder':'5'}))

class ProfileForm(ModelForm):
    class Meta:
        model = ShotgunProfile
        fields = ['avatar','school','year','passengers']

class SearchForm(forms.Form):
    fromInput = forms.CharField(required=False, widget=forms.TextInput(attrs={'id':'address-from', 'class':'col-xs-12','autocomplete':'off'}), max_length=255)
    fromLat = forms.DecimalField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'lat'}), max_digits=20, decimal_places=16)
    fromLng = forms.DecimalField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'lng'}), max_digits=20, decimal_places=16)
    fromFormatted = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'formatted_address'}), max_length=255)
    fromLocality = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'locality'}), max_length=255)

    toInput = forms.CharField(required=False, widget=forms.TextInput(attrs={'id':'address-to', 'class':'col-xs-12','autocomplete':'off'}), max_length=255)
    toLat = forms.DecimalField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'lat'}), max_digits=20, decimal_places=16)
    toLng = forms.DecimalField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'lng'}), max_digits=20, decimal_places=16)
    toFormatted = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'formatted_address'}), max_length=255)
    toLocality = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'data-geo':'locality'}), max_length=255)

    leavingOn = forms.DateField(required=False, widget=forms.DateInput(attrs={'class':'col-xs-12','placeholder':'mm/dd/yyyy'}))

shotgun/resources/templates/rides/index.html
{% extends 'layout_header.html' %}

{% block content %}

    {# This should be fixed to the top right #}
     
    </script>


    {# This is the list of rides #}
    <div class="col-md-5">
    <section id="section-ride-index">

        {% for ride in rides %}
            
            
            <div class="ride">
                {#<img src="#" alt="Driver Image">#}
               <div id="img"></div>
                <h2>{{ride.driver.username}}</h2>
                <h4>From {{ride.fromLocation.city}} to {{ride.toLocation.city}}</h4>
                <p>
                    {{ride.driver.shotgunprofile.school}} |
                    {{ride.driver.shotgunprofile.year}}<br>
                    Types of Passengers: {{ride.driver.shotgunprofile.passengers}}<br>
                    
                </p>
            </div>

        {% endfor %}

    </section>
    </div>
    
        <div class="col-md-6 col-md-offset-1">
        <div id="ride-map">
        
        </div>
    </div>


{% endblock %}

shotgun/resources/templates/rides/new.html
{% extends 'layout_header.html' %}

{% block head %}
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    <script src="{{ STATIC_URL }}js/jquery.geocomplete.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/shotgun.map.js"></script>
    <script>

        $(document).ready(function(){
            $("#address-from").geocomplete({details: "#details-from", detailsAttribute: "data-geo"});
            $("#address-to").geocomplete({details: "#details-to", detailsAttribute: "data-geo"});
            $( "#id_leavingOn" ).datepicker();

            $("#address-from")
                .geocomplete()
                .bind("geocode:result", function(event, result){

                    if(!$('#id_toLat').val()) {
                        drawMarker(result.geometry.location.lat(), result.geometry.location.lng());
                    } else {
                        drawRoute(result.geometry.location.lat(), result.geometry.location.lng(), $('#id_toLat').val(), $('#id_toLng').val());
                    }
                }
            );

            $("#address-to")
                .geocomplete()
                .bind("geocode:result", function(event, result){

                    if(!$('#id_fromLat').val()) {
                        drawMarker(result.geometry.location.lat(), result.geometry.location.lng());
                    } else {
                        drawRoute($('#id_fromLat').val(), $('#id_fromLng').val(), result.geometry.location.lat(), result.geometry.location.lng());
                    }
                }
            );

        });
    </script>
{% endblock %}

{% block navbar %}{% include 'navbar.html' with active='add' %}{% endblock %}

{% block content %}
    
    <section id="section-ride-new">
        <form action="" method="post" class="form-inline" role="form" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Add a Ride</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="address-from">From:</label><br>
                            {{rideForm.fromInput}}
                            {{rideForm.fromInput.errors}}

                            <label for="address-to">To:</label><br>
                            {{rideForm.toInput}}
                            {{rideForm.toInput.errors}}

                            <label for="id_leavingOn">Leaving On:</label><br>
                            {{rideForm.leavingOn}}
                            {{rideForm.leavingOn.errors}}

                            <label for="id_gasMoney">Gas Money ($):</label><br>
                            {{rideForm.gasMoney}}
                            <span class="help-block"><span class="glyphicon glyphicon-info-sign"></span> How much gas money are you asking passengers to pay?</span>
                            {{rideForm.gasMoney.errors}}

                            <label for="id_luggageRoom">Luggage Room:</label><br>
                            {{rideForm.luggageRoom}}
                            <span class="help-block"><span class="glyphicon glyphicon-info-sign"></span> How many passenger bags can you fit in your car?</span>
                            
                            {{rideForm.luggageRoom.errors}}

                            <span id="details-from">
                                {{rideForm.fromLat}}
                                {{rideForm.fromLng}}
                                {{rideForm.fromFormatted}}
                                {{rideForm.fromLocality}}
                            </span>

                            <span id="details-to">
                                {{rideForm.toLat}}
                                {{rideForm.toLng}}
                                {{rideForm.toFormatted}}
                                {{rideForm.toLocality}}
                            </span>
                        </div>
                        <div class="col-md-6">
                            <div id="map_canvas" class="map-new">
                                <div style="width: 100%; text-align: center; padding: 140px">Type an address to get started!</div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12" style="text-align: center">
                            <input type="submit" value="Post Your Ride!" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>  
        </form>
    </section>

{% endblock %}

shotgun/resources/templates/rides/ride.html
<div class="ride">
   {% if ride.driver.shotgunprofile.avatar.url != "/uploads/False" %}<div class="img"><img src="{{ ride.driver.shotgunprofile.avatar.url }}" alt="Driver Image"></div>{% endif %}
    <h3><a href="{% url 'rides_show' pk=ride.id %}">{{ride.fromLocation.city}} to {{ride.toLocation.city}}</a></h3>
    <h4>{{ride.driver.username}}</h4>
    <p>
        {{ride.leavingOn}}<br>
        {{ride.driver.shotgunprofile.school}} |
        {{ride.driver.shotgunprofile.year}}<br>
        Types of Passengers: {{ride.driver.shotgunprofile.passengers}}<br>
    </p>
</div>

shotgun/resources/templates/rides/search.html
{% extends 'layout_header.html' %}

{% block head %}
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyArTylJf9gxDN3uns-Wrmnh9drOb9xmMFU&sensor=false&libraries=places,drawing"></script>
    <script src="{{ STATIC_URL }}js/jquery.geocomplete.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/shotgun.map.js"></script>
    <script>

        $(document).ready(function(){
            $("#address-from").geocomplete({details: "#details-from", detailsAttribute: "data-geo"});
            $("#address-to").geocomplete({details: "#details-to", detailsAttribute: "data-geo"});
            $( "#id_leavingOn" ).datepicker();

            $("#address-from")
                .geocomplete()
                .bind("geocode:result", function(event, result){

                    if(!$('#id_toLat').val()) {
                        drawMarker(result.geometry.location.lat(), result.geometry.location.lng());
                    } else {
                        drawRoute(result.geometry.location.lat(), result.geometry.location.lng(), $('#id_toLat').val(), $('#id_toLng').val());
                    }

                    $("#map-row").slideDown();
                    $("#results-row").fadeOut();
                }
            );

            $("#address-to")
                .geocomplete()
                .bind("geocode:result", function(event, result){

                    if(!$('#id_fromLat').val()) {
                        drawMarker(result.geometry.location.lat(), result.geometry.location.lng());
                    } else {
                        drawRoute($('#id_fromLat').val(), $('#id_fromLng').val(), result.geometry.location.lat(), result.geometry.location.lng());
                    }

                    $("#map-row").slideDown();
                    $("#results-row").fadeOut();
                }
            );

        });
        
    </script>

{% endblock %}

{% block content %}

    <section id="section-ride-search">

        {% if not query %}
        
        {% endif %}
            <div class="row">
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Find a Ride</h2>
                        </div>
                    </div>

                    <form action="" method="post" class="form-inline" role="form" autocomplete="off">
                        {% csrf_token %}
                        <div class="row">
                                <div class="col-sm-12 col-md-4">
                                    <label for="address-from">From:</label><br>
                                    {{form.fromInput}}
                                    {{form.fromInput.errors}}
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    <label for="address-to">To:</label><br>
                                    {{form.toInput}}
                                    {{form.toInput.errors}}                            
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    <label for="id_leavingOn">Leaving On:</label><br>
                                    {{form.leavingOn}}
                                    {{form.leavingOn.errors}}                            
                                </div>

                                <span id="details-from">
                                    {{form.fromLat}}
                                    {{form.fromLng}}
                                    {{form.fromFormatted}}
                                    {{form.fromLocality}}
                                </span>

                                <span id="details-to">
                                    {{form.toLat}}
                                    {{form.toLng}}
                                    {{form.toFormatted}}
                                    {{form.toLocality}}
                                </span>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-sm-offset-3" style="padding: 20px 15px 20px 15px">
                                <input type="submit" value="Search" class="btn btn-primary col-xs-12" />
                            </div>
                        </div>
                    </form>

                    <div class="row" id="map-row"{% if not fromLat and not toLat %} style="display: none"{% endif %}>
                        <div class="col-md-12">
                            <div id="map_canvas" class="map-ride-new col-md-12"></div>
                        </div>
                    </div>

                    <div class="row" id="results-row">
                        <div class="col-md-12">
                            {% for result in page.object_list %}
                                {% if result.object.id %}
                                    {% include 'rides/ride.html' with ride=result.object %} 
                                {% endif %}
                            {% empty %}
                                <p class="col-xs-12" style="text-align: center">No results found. Try another search?</p>
                            {% endfor %}

                            {% if page.has_previous or page.has_next %}
                                <div>
                                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                                    |
                                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                                </div>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>  

    </section>

    <script>
        {% if fromLat and toLat %}
            drawRoute({{fromLat}}, {{fromLng}}, {{toLat}}, {{toLng}});
        {% elif fromLat %}
            drawMarker({{fromLat}}, {{fromLng}});
        {% elif toLat %}
            drawMarker({{toLat}}, {{toLng}});
        {% endif %}
    </script>

{% endblock %}

shotgun/resources/templates/rides/show.html
{% extends 'layout_header.html' %}

{% block content %}

    {# This is the list of rides #}
    <section id="section-ride-index">

        <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1">
                <div class="row">
                    <div class="col-xs-12">
                        <h2>Find a Ride</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {% include 'rides/ride.html' with ride=ride %}
                        {% if user.is_authenticated %}
                            <div class="row">
                                <div class="col-xs-12">
                                    <a href="mailto:{{ride.driver.email}}" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-envelope"></span> Email this Driver</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col-xs-12">
                                    <a href="{% url 'home' %}" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-envelope"></span> Log In to Email this Driver</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="row visible-sm visible-xs"><div class="col-xs-12">&nbsp;</div></div>
                    <div class="col-md-6">
                        <div id="map_canvas" class="col-xs-12"></div>
                    </div>
                </div>
            </div>
        </div>
    
    </section>


{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArTylJf9gxDN3uns-Wrmnh9drOb9xmMFU&sensor=true"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/shotgun.map.js"></script>

    <script type="text/javascript">
        drawRoute({{ride.fromLocation.lat}}, {{ride.fromLocation.lng}}, {{ride.toLocation.lat}}, {{ride.toLocation.lng}});
    </script>
{% endblock %}